services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kommandhub\PaystackSW\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Kommandhub\PaystackSW\Checkout\Payment\Processor\TransactionVerificationProcessorInterface:
    alias: Kommandhub\PaystackSW\Checkout\Payment\Processor\TransactionVerificationProcessor

  Kommandhub\PaystackSW\Checkout\Payment\Processor\TransactionMetadataProcessorInterface:
    alias: Kommandhub\PaystackSW\Checkout\Payment\Processor\TransactionMetadataProcessor

  Kommandhub\PaystackSW\Checkout\Payment\PaystackPaymentHandler:
    tags:
      - { name: 'shopware.payment_handler' }

  Kommandhub\PaystackSW\Administration\Controller\RefundController:
    arguments:
      $paystack: '@Kommandhub\PaystackSW\Service\Paystack'
    tags:
      - { name: 'container.service', method: 'setContainer' }
    calls:
      - [setContainer, ['@service_container']]
    public: true

  Kommandhub\PaystackSW\Storefront\Controller\WebhookController:
    public: true
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ ]